version: "3.1"

services:
  db:
    image: mysql/mysql-server:8.0.27
    restart: always
    command:
      [
        "mysqld",
        "--sql-mode=NO_ENGINE_SUBSTITUTION",
        "--default-authentication-plugin=mysql_native_password",
      ]
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 123456
